# -*- coding: utf-8 -*-
"""Retail Sales Analysis Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqHCWVh9jQpAKYZsyEToB9vLFRfRBD1o
"""

from google.colab import files
uploaded = files.upload()

import os
os.listdir()

import pandas as pd

df = pd.read_csv("retail_sales_dataset (1).csv")
df.head()

df.info()

df.columns

import matplotlib.pyplot as plt

df.groupby("Product Category")["Total Amount"].sum().plot(kind="bar")

plt.title("Sales by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Total Amount")
plt.show()

import matplotlib.pyplot as plt

plt.scatter(df["Quantity"], df["Total Amount"])
plt.title("Quantity vs Total Amount")
plt.xlabel("Quantity")
plt.ylabel("Total Amount")
plt.show()

df.groupby("Gender")["Total Amount"].sum().plot(kind="bar")

plt.title("Sales by Gender")
plt.ylabel("Total Amount")
plt.show()

df.groupby("Age")["Total Amount"].sum().plot(kind="line")

plt.title("Age vs Spending")
plt.xlabel("Age")
plt.ylabel("Total Amount")
plt.show()

df["Date"] = pd.to_datetime(df["Date"])

df["Month"] = df["Date"].dt.to_period("M")

df.groupby("Month")["Total Amount"].sum().plot(kind="line")

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Amount")
plt.show()

df.groupby("Customer ID")["Total Amount"].sum().sort_values(ascending=False).head(5).plot(kind="bar")

plt.title("Top 5 Customers")
plt.ylabel("Total Amount")
plt.show()

print("Total Sales:", df["Total Amount"].sum())
print("Total Customers:", df["Customer ID"].nunique())
print("Total Products:", df["Product Category"].nunique())

import pandas as pd

pd.crosstab(df["Gender"], df["Product Category"]).plot(kind="bar", stacked=True)

plt.title("Gender vs Product Category")
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(12,10))

df.groupby("Product Category")["Total Amount"].sum().plot(kind="bar", ax=axes[0,0])
axes[0,0].set_title("Sales by Category")

df.groupby("Gender")["Total Amount"].sum().plot(kind="bar", ax=axes[0,1])
axes[0,1].set_title("Sales by Gender")

df.groupby("Age")["Total Amount"].sum().plot(kind="line", ax=axes[1,0])
axes[1,0].set_title("Age vs Sales")

df.groupby("Month")["Total Amount"].sum().plot(kind="line", ax=axes[1,1])
axes[1,1].set_title("Monthly Trend")

plt.tight_layout()
plt.show()